name: 'Example composite GitHub action'
description: 'Example composite GitHub action'
author: hello@cloudposse.com
branding:
  icon: 'file'
  color: 'white'
inputs:
  sha:
    required: true
    description: "Input parameter placeholder"
    default: "true"
runs:
  using: 'node16'
  main: 'src/index.js'
