name: auto-release

on:
  push:
    branches:
      - main

jobs:
  auto:
    uses: cloudposse/.github/.github/workflows/shared-auto-release.yml@shared-auto-release
    with:
      publish: true
      prerelease: false
      config-name: auto-release-config.yml
    secrets: inherit
