name: auto-release

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: auto-release
    steps:
      - uses: actions/create-github-app-token@v1
        id: github-app
        with:
          app-id: ${{ vars.BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}

      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: cloudposse/github-action-auto-release@v1
        with:
          publish: true
          prerelease: false
          token: ${{ steps.github-app.outputs.token }}
          config-name: auto-release-config.yml