name: Main branch
on:
  push:
    branches:
      - main
      - release/v*

permissions:
  contents: write
  actions: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo "${{ toJSON(github) }}"
        
  perform:
    uses: cloudposse/github-actions-workflows-github-action-composite/.github/workflows/main-branch.yml@get-rid-pat
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"
    secrets: inherit