name: Terraform provider Release
on:
  push:
    tags:
      - '*.*.*'

permissions:
  id-token: write
  contents: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo '${{ toJSON(github) }}'

  perform:
    uses: cloudposse/.github/.github/workflows/shared-tf-provider-release.yml@get-rid-pat
    with:
      version: ${{ github.event.release.tag_name }}
    secrets: inherit